"""tables

Revision ID: fb2097aa30ae
Revises: 9bdf302dc90c
Create Date: 2024-10-30 16:35:08.135091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb2097aa30ae'
down_revision = '9bdf302dc90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(), nullable=False))
        batch_op.drop_column('usernamer')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usernamer', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('username')

    # ### end Alembic commands ###
